version: "3.9"

services:
  storefront: 
    build:
      context: storefront/.
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
    profiles:
      - store_front
  
  sheduler:
    build:
      context: sheduler/.
    ports:
      - "81:80"
    profiles:
      - sheduler

  database: 
    image: "mysql"
    env_file: 
      - ./mysql/env_vars
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - kinetco:/var/lib/mysql
    profiles:
      - store_front
      - sheduler
      
volumes:
  kinetco: