version: "3.9"

services:
  storefront: 
    build:
      context: .
      args:
        - region=us-west-2
        - alice=0
      environment:
        - runtime_env=dev
  database: 
    image: "mysql"
    env_file: 
      - ./mysql_vars/mysql_env
