version: "3.9"

services:
  storefront: 
    build:
      context: storefront/.
    ports:
      - "80:80"
      - "443:443"
  
  sheduler:
    build:
      context: sheduler/.
    ports:
      - "81:80"

  database: 
    image: "mysql"
    env_file: 
      - ./mysql/env_vars
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - kinetco:/var/lib/mysql

volumes:
  kinetco: