version: "3.9"

services:
  storefront: 
    build:
      context: .
  database: 
    image: "mysql"
    env_file: 
      - ./mysql_vars/mysql_env
    volumes:
      - ./mysql_vars:/docker-entrypoint-initdb.d:ro